### ISSUE TITLE
Mica/Acryl does not work, even on Windows 11

### ISSUE THREAD

**Issue by onionware-github** [voidZiAD/WinBlur#3]
![image](https://user-images.githubusercontent.com/91136545/227999658-7a5c2dcf-9d55-4856-bea8-88de501e32b4.png)
I just get a black window background. This is a newly created WinForms app with one button in the middle.
Here is my Form1 code, everything else is the default. Mica is enabled in my Windows 11 system.
```
    public partial class Form1 : Form
	{
		
		public Form1()
        {
            InitializeComponent();
            this.Load += new EventHandler(Form1_Load);
		}

		private void button1_Click(object sender, EventArgs e)
		{
			MessageBox.Show("Witti.exe", "Moin Mica!");
		}

		private void Form1_Load(object sender, EventArgs e)
		{
			this.BackColor = Color.Black;
			UI.SetBlurStyle(cntrl: this, blurType: UI.BlurType.Mica, designMode: UI.Mode.DarkMode);
		}
	}
```

**Comment by xauuzd** [comment]
Have you compiled the new source code yourself and used the output DLL or have you used an official release of WinBlur?

**Comment by onionware-github** [comment]
> 

I use this package from nuget: https://www.nuget.org/packages/WinBlur

**Comment by xauuzd** [comment]
Hmm. Interesting.

It's been working for me and others who have used it, considering it has many downloads and only now has someone created an issue about it not working. Have you tried to ask anyone to test your version on their side? Because it could just be from your side.

**Comment by xauuzd** [comment]
[WinBlurTest.zip](https://github.com/Pronner/WinBlur/files/11081131/WinBlurTest.zip)

Maybe try to use this ^^
It works for me, so if it does not work for you then there's definitely something wrong on your side!

**Comment by onionware-github** [comment]
> [WinBlurTest.zip](https://github.com/Pronner/WinBlur/files/11081131/WinBlurTest.zip)
> 
> Maybe try to use this ^^ It works for me, so if it does not work for you then there's definitely something wrong on your side!

Ok, I also don't know why it does not work. It is still just black.
PS: I'm running it inside a VM, because I use Windows 10 on my main PC. Other Mica apps working fine. Can you also test it in a VM?
![image](https://user-images.githubusercontent.com/91136545/228024742-844b0529-367e-4b08-9f0a-18dc6bfc3398.png)
