### ISSUE TITLE
Light Mode cannot display a matching Fore Color.

### ISSUE THREAD

**Issue by Marvinware** [voidZiAD/WinBlur#4]
The light mode works very buggy for me. The fore color of objects (labels, picture box and much more) cannot be changed further in light mode. I can't adapt to myself. I am using Visual Basic WinForms Net 4.8

![Screenshot 2023-03-29 140410](https://user-images.githubusercontent.com/37700409/228533580-67b80453-f852-45f6-aa67-6ebd5d17cf1d.png)

![Screenshot 2023-03-29 140421](https://user-images.githubusercontent.com/37700409/228533590-b457c6b1-b16d-4a6c-b11b-d6b234ecca71.png)

`
Imports WinBlur
Imports WinBlur.UI
Public Class Form1

    Private Sub Form1_Load(sender As Object, e As EventArgs) Handles MyBase.Load
        Me.BackColor = Color.Black
        Me.ForeColor = Color.White
        SetBlurStyle(Me, BlurType.Mica, Mode.DarkMode)
        Me.BackColor = Color.Black
        Me.ForeColor = Color.White
    End Sub

    Private Sub Button1_Click(sender As Object, e As EventArgs) Handles Button1.Click
        Me.BackColor = Color.White
        SetBlurStyle(Me, BlurType.Mica, Mode.LightMode)
        Me.BackColor = Color.White
        Me.ForeColor = Color.DimGray
    End Sub

    Private Sub Button2_Click(sender As Object, e As EventArgs) Handles Button2.Click
        Me.BackColor = Color.Black
        Me.ForeColor = Color.White
        SetBlurStyle(Me, BlurType.Mica, Mode.DarkMode)
        Me.BackColor = Color.Black
        Me.ForeColor = Color.White
    End Sub
End Class
`
[Mica Test.zip](https://github.com/Pronner/WinBlur/files/11100876/Mica.Test.zip)

**Comment by xauuzd** [comment]
What do you mean by cannot be changed further in light mode? Can you be more clear with your issue?

**Comment by xauuzd** [comment]
Yeah, I've seen the issue now after testing your source code. I will be trying to fix this, because I also tried manually changing the Forecolor of the buttons but it still didn't work. What I can recommend is using a framework like Guna UI/Bunifu until this gets fixed. But by the way Acrylic Light mode works fine.

Either way, let's be honest, no one likes/uses light mode unless they want to become blind.

Thank you for reporting this issue anyways.

**Comment by BugattiV** [comment]
![_](https://user-images.githubusercontent.com/117547955/232485275-46b7dd64-64d5-465e-9ae4-bce365f7b967.png)

Acrylic dark theme.
The form's background color is black.

Can we make the background darker?
[https://learn.microsoft.com/en-us/windows/apps/design/style/acrylic](url)
![_](https://learn.microsoft.com/en-us/windows/apps/design/style/images/luminosity-vs-tint.png)

**Comment by xauuzd** [comment]
You could try using RGBA.

`...Color = new Color.FromARGB(0, 0, 0);`

That should be the maximum level of dark. More than that is not possible.
