### ISSUE TITLE
Presenting Problems and Suggestions

### ISSUE THREAD

**Issue by adilsonxavierfernando** [voidZiAD/WinBlur#5]
Hello, I found quite interesting the work... I searched a lot for a solution that would allow me to create fluent interfaces, with Acrylic or Mica style, and I didn't find good material and anywhere... I found his project and enjoyed it a lot, because it almost solved my problem.
**Problem:**
Unfortunately, when testing it, he modified the control as intended, but damaged the design of the controls that constitute it. The text of the buttons looked strange, and the colors of the text, whether of buttons or labels, became blurry and weird... Already the text of the textbox, does not appreciate more ...

**Suggest:**
I would like to suggest that the same blurring mechanism be implemented for the controls as well, ex 
`SetBlurStyle(panel1, BlurType.Acrylic, Mode.LightMode);`
 where the backdroop will be an image that put as a backround of its containment element

**Comment by xauuzd** [comment]
Hello!

Thanks for your feedback on my project.
I apologize, but I no longer work on projects on my GitHub. Hence, if you have an idea on how you may be able to fix the issue, the source code is always available!

If you end up fixing the issue, I'd appreciate if you forked the project, and made pushed your fixed version onto the current existing one with the issue you're facing. Please make sure to specify the issue if it was fixed & how you fixed it, and you may also implement your suggestion.

This GitHub Issue will stay open until someone volunteers to fix it.
I hope WinBlur will continue to benefit you and your project. ✌️
