### ISSUE TITLE
No longer working?

### ISSUE THREAD

**Issue by Pxrallel** [voidZiAD/WinBlur#6]
I've tried implementing this in to a app just to test it and it doesn't seem to be working the form just turns completely black or white depending on the mode   

![image](https://github.com/voidZiAD/WinBlur/assets/70773976/2f31480f-78f3-4796-99ea-0c3c4a97a697)

**Comment by ozanbalci** [comment]
Your platform will get Windows 10 Sabahat Moon. If your platform is not
Windows 11, it will never work. because it uses windows 11 libraries

9 Ağu 2023 Çar 19:00 tarihinde Pxrallel ***@***.***> şunu
yazdı:

**Comment by Pxrallel** [comment]
I've upgraded to windows 11 and it doesn't seem to be working still
![image](https://github.com/voidZiAD/WinBlur/assets/70773976/c13ebda0-9b74-4da4-bc45-76e52a9eda86)

**Comment by xauuzd** [comment]
Hello @Pxrallel, I apologize for the late response. Haven't been using GitHub, since I don't really programme anymore.
Can you show me your code?

**Comment by xauuzd** [comment]
This may be helpful by the way: https://www.makeuseof.com/windows-11-transparency-not-working/

Not all versions of win11 have the transparency effect. The new versions definitely do have it, so you may have an old one that either has the setting disabled by default or does not have it at all.
