### ISSUE TITLE
WinBlur (Windows 10 & Above)

### ISSUE THREAD

**Issue by mevrzej** [voidZiAD/WinBlur#7]
Soo... it's not working on windows 10, i guess.
![focused](https://github.com/voidZiAD/WinBlur/assets/118586748/ea7deb62-da2e-4960-92e4-bc96037e811a)
![unfocused](https://github.com/voidZiAD/WinBlur/assets/118586748/35757d37-ca46-4570-8c16-19f8e07e4634)

**Comment by xauuzd** [comment]
This will work on the version of windows 10 that **supports these blur effects**. Please do your research and check if your windows version is compatible. If so, then it's likely that the setting is just **turned off** and you have to turn it off. Cheers!

**Comment by mevrzej** [comment]
> This will work on the version of windows 10 that **supports these blur effects**. Please do your research and check if your windows version is compatible. If so, then it's likely that the setting is just **turned off** and you have to turn it off. Cheers!

I did everything, and nothing work out, so i just installed win 11, and that fix this, so...
still thanks for your time and reply.
