### ISSUE TITLE
Button Text Not Being Readable

### ISSUE THREAD

**Issue by EhanChowdhury** [voidZiAD/WinBlur#8]
![image](https://github.com/voidZiAD/WinBlur/assets/81624666/148c373f-0c8c-476a-a3ec-2e881460bc59)
I'm having this issue with the button text how do I fix it?

**Comment by xauuzd** [comment]
I had the same issue yesterday. I don't know what the fix is, to be honest with you. I'll have to look into the code before I decide whether its fixable or not, otherwise WinBlur will be deemed unusable.

**Comment by xauuzd** [comment]
I just released a new version that *might have* fixed your issue. I have tested texts on buttons with the new version, it still doesn't look very good but it kind of does the job
