### ISSUE TITLE
No Blur

### ISSUE THREAD

**Issue by xVotexX** [voidZiAD/WinBlur#9]
Hi,

i'm not sure if I am missing something, but my form is only transparent. There is no blur at all.

My `FormBorderStyle` is set to `None`
This is the code I tested with:

```csharp
using System;
using System.Drawing;
using System.Windows.Forms;
using WinBlur;
using static WinBlur.UI;

namespace WindowsFormsApp2
{
    public partial class Popup : Form
    {

        public Popup()
        {
            InitializeComponent();
            this.BackColor = Color.Black;
            SetBlurStyle(cntrl: this, blurType: BlurType.Acrylic, designMode: Mode.DarkMode);
        }

        private void Popup_Load(object sender, EventArgs e)
        {

        }
    }
}
```
**The X in the middle is from the popup form, which should be transparent and blurred.**
![image](https://github.com/voidZiAD/WinBlur/assets/160360993/9fc4fbc3-66c1-4bfa-874d-25961f053ad4)

**Comment by xauuzd** [comment]
Unfortunately, the blur effect works ONLY on WindowTypes other than "None". There could be a fix, I am currently seeing what I can improve in this project or fix. But, it's likely that this is something that cannot be fixed and it's a feature by Windows, where only default WindowType/Style is going to be blurred.

**Comment by xauuzd** [comment]
Btw, by WindowTypes/Style I meant FormBorderStyle. My bad.

**Comment by xauuzd** [comment]
Here's a temporary fix!

(This should be in your form btw)

```cs
protected override CreateParams CreateParams
{
    get
    {
        int WS_DLGFRAME = 0x400000;
        CreateParams result = base.CreateParams;
        result.Style &= ~WS_DLGFRAME;
        return result;
    }
}
```

This should allow you to use the Effect while not seeing the default border/title and implementing your own border and top bar. Btw, the FormBorderStyle should not be None, so technically this isn't a fix, but it works. I will still be looking into a way to fix this.

**Comment by xVotexX** [comment]
Thanks for your reply! I have now set my FormBorderStyle to Sizeable but I don't quite understand where exactly I should put your fix. Can you please give me a full code example as in my original message?

**Comment by xauuzd** [comment]
Here's a code example:

```cs
using System;
using System.Windows.Forms;
using WinBlur;

namespace WinBlurTest
{
    public partial class Form1 : Form
    {

        protected override CreateParams CreateParams
        {
            get
            {
                int WS_DLGFRAME = 0x400000;
                CreateParams result = base.CreateParams;
                result.Style &= ~WS_DLGFRAME;
                return result;
            }
        }

        public Form1()
        {
            InitializeComponent();
            UI.SetBlurStyle(cntrl: this, blurType: UI.BlurType.Acrylic, designMode: UI.Mode.DarkMode);
        }
        
        private void Form1_Load(object sender, EventArgs e)
        {


        }
    }
}

```

It should be at the top of the class

**Comment by xauuzd** [comment]
Let me know if it works. I noticed that it doesn't ALWAYS work, but let me know. it should look like this:
![Screenshot (1)](https://github.com/voidZiAD/WinBlur/assets/84229419/560ea639-fd51-4efa-bb22-30b4d8c574aa)

**Comment by xVotexX** [comment]
In my case, the form is just black. In the Designer i set the BackColor to Standart `Control`

```csharp
using System;
using System.Drawing;
using System.Windows.Forms;
using WinBlur;
using static WinBlur.UI;

namespace WindowsFormsApp2
{
    public partial class Popup : Form
    {

        protected override CreateParams CreateParams
        {
            get
            {
                int WS_DLGFRAME = 0x400000;
                CreateParams result = base.CreateParams;
                result.Style &= ~WS_DLGFRAME;
                return result;
            }
        }

        public Popup()
        {
            InitializeComponent();
            UI.SetBlurStyle(cntrl: this, blurType: UI.BlurType.Acrylic, designMode: UI.Mode.DarkMode);
        }

        private void Popup_Load(object sender, EventArgs e)
        {

        }
    }
}
```

![image](https://github.com/voidZiAD/WinBlur/assets/160360993/5f915fa1-2208-4354-9710-70f3996cdad1)

**Comment by xVotexX** [comment]
I've just noticed that when the Form is focused, everything is black, but when I click anywhere else, it changes its BackColor.

![focusgif](https://github.com/voidZiAD/WinBlur/assets/160360993/43be3eb3-3027-43b6-93d4-135669da821d)

**Comment by xauuzd** [comment]
Thing is, I noticed you have to minimize and reopen the form for it to work. Also, perhaps there's a backcolor that's tampering with the color. You might've set the backcolor of a Panel for example as Black. Anyways, if it still doesn't work, then like I said this is a temporary solution. I will be working on a better solution and I'll update the package once I have done it.

**Comment by xVotexX** [comment]
The problem now is that even if I remove your fix, the background is still not what it should be. Now it's not even just transparent. Minimising and reopening does not help.

```csharp
using System;
using System.Drawing;
using System.Windows.Forms;
using WinBlur;
using static WinBlur.UI;

namespace WindowsFormsApp2
{
    public partial class Popup : Form
    {


        public Popup()
        {
            InitializeComponent();
            SetBlurStyle(cntrl: this, blurType: BlurType.Acrylic, designMode: Mode.DarkMode);
        }

        private void Popup_Load(object sender, EventArgs e)
        {

        }
    }
}
```
![image](https://github.com/voidZiAD/WinBlur/assets/160360993/5265cdbf-520f-4a9f-af88-f37d14e62e8d)

**Comment by xauuzd** [comment]
I just realized... Are you on Windows 10?
Dude 😭 This doesn't work on Windows 10. The Blur effects have been introduced in Windows 11 and only a very very few versions of Windows 10. Perhaps the final versions, and even then, you'd have to do some work to enable the Effects. I'm sorry, but it's your OS, not the package.

Your original issue is still valid though, and I am still gonna work on fixing it.

**Comment by xVotexX** [comment]
Damn. Thats sad. You should remove the "Windows 10" in your [Readme](https://github.com/voidZiAD/WinBlur?tab=readme-ov-file#-winblur-windows-10--above) then i guess. 
Do you know anything similar that works on Win10?

**Comment by xauuzd** [comment]
Well. It does work on Win10, so It's not incorrect. It's just that, it doesn't work on all versions, and you have to enable it most of the time.

And unfortunately there are no blur effects supported on Versions below 10-11, unless you create it yourself via the Form using user controls and code.

**Comment by xVotexX** [comment]
Too bad. Good luck then
